name: SetMaxHealth
version: '1.1.0'
main: lyu.leo.setmaxhealth.SetMaxHealth
api-version: '1.20'

commands:
  SetMaxHealth:
    description: Sets the max health of you or another player.
    usage: /setmaxhealth <playername> <HealthPoints>
    permission: setmaxhealth.set
  SetLocked:
    description: Adds or removes players that can be locked from a max-health change.
    usage: /setLocked [add|remove] <playername>
    permission: setlocked.set