name: SetMaxHealth
version: '1.0-SNAPSHOT'
main: lyu.leo.setmaxhealth.SetMaxHealth
api-version: '1.20'

commands:
  SetMaxHealth:
    description: Sets the max health of you or another player.
    usage: /setmaxhealth
    permission: setmaxhealth.set